language: ruby
rvm:
- 2.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

before_install:
  - pip install html5validator
script:
  - bundle exec jekyll build
    # htmlproof is not build-breaking (yet)
  - bundle exec htmlproof build --disable-external --check-html --alt-ignore '/piwik\.php/' --check-favicon || exit 0
  - html5validator --root build
